import Banner from "./banner";

export default function Home() {
  return (
    <div className="home-banner">
      <Banner />
      <code>[Full Stack Developer]</code>
      <section className="code-logos">
        <img
          alt="TypeScript"
          width="30px"
          src="https://cdn.jsdelivr.net/gh/devicons/devicon/icons/typescript/typescript-plain.svg"
        />
        <img
          alt="Nextjs"
          width="30px"
          className="dark"
          src="https://cdn.jsdelivr.net/gh/devicons/devicon/icons/nextjs/nextjs-original-wordmark.svg"
        />
        <img
          alt="Vim"
          width="30px"
          src="https://cdn.jsdelivr.net/gh/devicons/devicon/icons/vim/vim-original.svg"
        />
        <img
          alt="Git"
          width="30px"
          src="https://cdn.jsdelivr.net/gh/devicons/devicon/icons/git/git-original.svg"
        />
        <img
          alt="Linux"
          width="30px"
          src="https://cdn.jsdelivr.net/gh/devicons/devicon/icons/linux/linux-original.svg"
        />
        <img
          alt="HTML"
          width="30px"
          src="https://cdn.jsdelivr.net/gh/devicons/devicon/icons/html5/html5-plain.svg"
        />
        <img
          alt="CSS"
          width="30px"
          src="https://cdn.jsdelivr.net/gh/devicons/devicon/icons/css3/css3-plain.svg"
        />
        <img
          alt="JavaScript"
          width="30px"
          src="https://cdn.jsdelivr.net/gh/devicons/devicon/icons/javascript/javascript-plain.svg"
        />
        <img
          alt="React"
          width="30px"
          src="https://cdn.jsdelivr.net/gh/devicons/devicon/icons/react/react-original.svg"
        />
        <img
          alt="NodeJS"
          width="30px"
          src="https://cdn.jsdelivr.net/gh/devicons/devicon/icons/nodejs/nodejs-original.svg"
        />
        <img
          alt="Python"
          width="30px"
          src="https://cdn.jsdelivr.net/gh/devicons/devicon/icons/python/python-plain.svg"
        />
        <img
          alt="GitHub"
          width="30px"
          className="dark"
          src="https://cdn.jsdelivr.net/gh/devicons/devicon/icons/github/github-original.svg"
        />
        <img
          alt="Bash"
          width="30px"
          className="dark"
          src="https://cdn.jsdelivr.net/gh/devicons/devicon/icons/bash/bash-original.svg"
        />
        <img
          alt="php"
          width="30px"
          src="https://cdn.jsdelivr.net/gh/devicons/devicon/icons/php/php-original.svg"
        />
        <img
          alt="raspberry-pi"
          width="30px"
          src="https://cdn.jsdelivr.net/gh/devicons/devicon/icons/raspberrypi/raspberrypi-original.svg"
        />
      </section>
    </div>
  );
}
